---
title: "Towards meta-scientific meta-analyses: standard operating procedures for meta-analysis in the Paluck Lab"
shorttitle: "Paluck_meta_SOP"
author:
 
  - name: "Seth A. Green"
    affiliation: "1"
    address: "Kahneman-Treisman Center, Princeton University"
    email: "sag2212@columbia.edu"
    role:
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name: "Elizabeth Levy Paluck"
    affiliation: "2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"
  - name: "Roni Porat"
    affiliation: "3"
    role:
      - "Writing - Review & Editing"
      - "Supervision"
affiliation:
  - id: "1"
    institution: "Kahneman-Treisman Center, Princeton University"
  - id: "2"
    institution: "Princeton University "
  - id: "3"
    institution: "Hebrew University, Jerusalem"
authornote: |
 This work was supported by [whoever supports it]. Thanks to Tara Slough, Don Green, and Alix Winter for valuable comments on an early draft.
abstract: |

 This paper describes the motivations and procedures for meta-analyses by Betsy Levy Paluck and co-authors, with reference to and examples drawn from three such papers [@paluck2019; @paluck2021; @porat2024]. We first describe how our meta-analyses advance the meta-scientific goals of critically assessing the robustness of a literature's core findings with respect to differences in study design, measurement strategy, intervention approach, and estimand. We also detail where we think quantitative reviews add value and how we think through the trade-off between comprehensive and selective inclusion criteria. Second, we describe the typical 'flow' of the papers as a whole. Third, we describe our meta-analytic procedures, detailing our default analytic choices and introducing an R package that implements those choices. These 'Standard Operating Procedures' are intended as a guide to a handful of especially thorny meta-analytic issues. We conclude with some open questions for meta-analysts.

keywords: "meta-analysis, standard-operating-procedures, meta-science"
wordcount: "7508"
bibliography: "meta-sop-references.bib"
floatsintext: no
linenumbers: no
draft: no
mask: no
figurelist: no
tablelist: no
footnotelist: no
class: "jou"
output: papaja::apa6_pdf
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE, echo=FALSE, eval=FALSE}
source('./R/render_commit_push.R')
rcp <- render_commit_push

```

# Introduction: Bridging the gap between meta-analysis and meta-science

What purposes do meta-analyses serve above and beyond those accomplished by systematic reviews? Judging by recent papers in social psychology [@pettigrew2006; @bem2015; @cuddy2018; @bezrukova2016], the answer is to bolster and validate existing findings through aggregation. By pooling findings from many studies, researchers furnish meta-analytic estimates that are statistically precise and drawn from diverse settings, giving readers the impression of durable, robust findings. Such papers often have a valedictory quality to them: they provide leading practitioners a chance to survey the body of work they've helped inspire, highlight the strength of the evidence for their subfield's central tenets, and suggest future research directions that assume those tenets are no longer in need of testing.

Meanwhile, a parallel movement in psychology has begun to implement the recommendations of the open science [@nosek2015] and meta-science [@schooler2014] movements into study designs [@ferguson2023], journal policies [@hardwicke2023], and literature reviews [@hardwicke2018]. Broadly speaking, meta-scientific papers aim to assess whether a literature's findings are credible. While meta-analyses seek to combine results, taken more or less at face value, meta-science papers, by contrast, ask whether the designs, analyses and implementations within a literature license its authors' inferences.

Some meta-scientific reviews quantitatively assess collective outcomes, for instance, what percentage of a subset of papers are computationally reproducible [@obels2020] or consistent with open data standards [@hardwicke2021]. In one sense, these estimates are 'meta-analytic,' but they aren't meta-analyses in the conventional sense of pooling existing findings into weighted average effects [@glass1977; @kleinstauber1996; @cooper2019]. In tone, meta-science papers are often much more critical than meta-analyses are, and they are often written by outsiders or newcomers to an academic field who appear more motivated to interrogate than to validate. Thus, their similar names notwithstanding, meta-analytic and meta-scientific papers in social psychology typically have radically different perspectives, assumptions, and goals.

At the Paluck lab, we seek to synthesize these two approaches by writing meta-analyses that are fundamentally meta-scientific. While writing three such papers [@paluck2009; @paluck2019; @paluck2021; @porat2024], we've developed distinct beliefs about when a meta-analysis is useful, how to structure such papers, and which specifications are sensible defaults. This paper articulates those beliefs, and aims to illuminate how meta-analysis might become a standard component of the meta-scientific toolkit.

## Implementing meta-analytic theory with Standard Operating Procedures 

A healthy literature has interrogated meta-analytic methods, noting common pitfalls [@greco2013], statistical errors [@kadlec2023], and practical limitations, e.g. a widespread lack of reproducibility [@lakens2017] or data availability [@CITE]. This paper sits in that tradition, but is a bit of an offshoot in that we are not attempting to correct statistical or practical mistakes in meta-analyses, but rather articulate what it is that we are trying to do when we write them. In this regard, this paper is closely in dialogue with two recent contributions that attempt to put meta-analysis on firmer theoretical footing.

@slough2023 "highlight the dangers of conflating conceptual differences across studies with statistical sources of variation" (p. 29). They argue that for studies to have target equivalence (the property of identifying "the same estimand" (p. 1)), they must have fundamentally *harmonized* contrasts and measurement strategies: the "substantive comparison across studies is the same" and "the outcome of interest is the same and it is measured in the same way" (p. 2). Absent these conditions, meta-analytic results might not be "meaningful and interpretable" (p. 2). Further, target equivalence cannot be achieved "solely with statistical techniques" (p. 23); it is a property, rather, of appropriate "design or inclusion criteria" (p. 2).

We agree that an internally and externally valid causal meta-analytic estimate requires harmonization of contrasts and outcomes, as well as a high degree of internal validity within constituent studies. However, we also think that meta-analytic estimates which do *not* meet these conditions \textemdash those that combine results from many different designs, or whose diverse outcomes bear an unknown relationship to the true outcome of interest \textemdash can still be useful and informative if we ascribe them _descriptive_ rather than causal interpretation. Meta-analyzing a literature without clear harmony of independent and dependent variables is a case where the underlying model might be "wrong" but still useful.

The other paper in this vein we look to is @simonsohn2022, who argue that while the typical meta-analysis in social psychology aims "to be comprehensive, results-focused and transcriptive," this is "misguided, leading to uninterpretable results that misrepresent research literatures." First, they argue that a desire for comprehensiveness typically leads the meta- analyst to average "studies of the highest quality" with "studies that lack internal validity or external validity, which are obtained using incorrect statistical techniques, or studies where results seem to arise from methodological artefacts." This throw-it-all-in-the-blender approach produces results that are "virtually guaranteed to lack a meaningful interpretation" (p. XXX) despite their superficial statistical precision. Second, the authors encourage meta-analysts to focus on studies' designs, rather than just their results, to provide "readers with information that they can use to evaluate" (p. XXX) the quality of a research literature for themselves. Rather than describing every study, meta-analysts "can succinctly describe and summarize common design failures...and provide detailed descriptions only of the studies they deem most important or compelling" (p. XXX) This advice ties closely to their last dictum to meta-analysts: to evaluate rather than to transcribe, i.e., detail the evidence from the very best studies, identify common methodological shortcomings of the literature as a whole, and, finally, "discuss what open questions remain and what kinds of evidence would help answer those questions" (p. XXX).

Our meta-analyses share these goals, and the authors cite @paluck2021 as an example of a meta-analysis that is "selective, design-focused, and evaluative" (p. XXX).  However, as mentioned above, we part ways from this paper in that we believe comprehensive meta-analytic estimates still have a place in the meta-scientist's toolkit, so long as those estimates are ascribed non-causal meaning and are used to contextualize more selective analyses.

This paper also builds on a tradition of Standard Operating Procedures (SOPs) in the behavioral and medical sciences [@rapport2013; @wallace2015; @lakens2023]. In particular, we look to @lin2016, which details how the Green lab at Columbia sets "default practices to guide decisions when issues arise that were not anticipated" in pre-analysis plans.

Like that paper, this article is not intended as a comprehensive guide. Specifically, we do not cover identifying an interesting question where aggregating results from many studies will be a useful estimation strategy or searching for those studies (see @paul2022meta for a concise, step-by-step treatment, as well as @cumpston2019 and @cooper2019 for textbook-length treatments of these questions). Instead, we describe how we tackle a few especially thorny issues relating to coding studies and aggregating their results. Most of this paper is about aggregation. Our default procedures are designed to help readers evaluate a body of research for themselves. We hope this will prove interesting and informative to other labs, but not definitive: we expect readers to adapt and expand our guidelines to meet their own needs. (See also @harrer2021,  @frank2024, chapter 16 and @lakens2022, chapter 11 for hands-on guides to meta-analysis with examples in `R`.) 

## The remainder of this paper

This paper is a hybrid of a conceptual analysis of meta-analyses in general and a report on how we in particular write them. The first section articulates our general approach to meta-analysis. The second describes our typical approach to writing meta-analytic papers. The third details our meta-analytic defaults and introduces an R package that implements them and helps us write papers. Our conclusion recaps and notes some open questions for our lab.

First, we describe our conceptual approach to meta-analysis. We believe that meta-analyses are useful for evaluating the strengths and weaknesses of large, heterogeneous literatures, especially those that bring multiple theoretical perspectives to bear. We further believe that condensing each study down to a point estimate (or cluster of estimates) and associated variance(s) can furnish useful meta-scientific quantities. We also detail our thinking about the trade-off between, on the one hand, comprehensive but potentially biased meta-analyses and, on the other, narrower quantitative reviews that set strict inclusion criteria around study designs, interventions, and/or dependent variables.

Second, we describe the default structure and analytic defaults for our quantitative reviews. Our papers explain the main ideas and trends in a literature, our search processes and meta-analytic methods, meta-analytic findings, and a review of open questions, while our quantitative sections are structured to first present a literature's findings at face value, and then analyze subsets of the literature based on differences in study design, measurement strategy, intervention approach, and estimand.

Third, we detail our meta-analytic defaults, e.g. a preference for Glass's $\Delta$ over Cohen's _d_, random effects over fixed effects estimates, and clustering our standard errors at the level of a study (as opposed to a paper or a team of authors). We then introduce an R package, `PaluckMetaSOP`, that contains functions to help us quickly and efficiently perform meta-analyses.

Fourth and finally, we conclude with some open questions for meta-scientific meta-analyses. Our meta-analyses straddle the line between inductive and deductive inquiries, and thus are not an easy fit with conventional approaches to checking researcher degrees of freedom, which assume a deductive approach. We also discuss our evolving thinking about incorporating indirect cues of study quality, such as statistical mistakes (a negative signal) or special attention devoted to reproducibility (a positive one), into our analyses in a principled way.

We now detail our conceptual aims when we write meta-analyses.

# The purpose of meta-analysis

The main goals of our meta-analyses are the goals of any systematic review: to evaluate a body of knowledge for its strengths, weaknesses, central findings, open questions and empirical limitations. We write broadly for any reader who is interested in the underlying question, but generally aim for a non-specialist audience. In our experience, a literature's most noteworthy contributions often come from researchers outside the core field (e.g. @mousa2020, @boisjoly2006, or @scacco2018 for the contact hypothesis, @munger2017 for anti-prejudice work, or @haushofer2019 for violence against women); to such researchers, we aim to provide signposts, in the form of unearthed, widespread empirical gaps and theoretical limitations, about where future empirical work will be most valuable. We also believe that funders and policymakers will benefit from systematic, critical reviews that do not take subject matter expertise for granted.

## What makes a literature a good candidate for meta-analysis?
Large, heterogeneous literatures, especially those with multiple theoretical perspectives, are good candidates for meta-analysis. In such cases, a meta-analysis might provide a useful contribution simply by dividing a literature into its constituent parts. For example, @paluck2021 categorizes 418 experiments published between 2007 and 2019 and organizes them into thirteen theoretical approaches and twelve categories of prejudice targeted. Simply identifying this heterogeneity of approaches and outcomes, along with describing a few constituent studies from the major theoretical strands in detail, helps the reader evaluate a literature's major findings for herself. She might reasonably wonder: does an intervention that aims to change political attitudes towards the rights of trans persons [@broockman2016] shed light on what might reduce tensions between castes in India [@lowe2021]? Is an extended contact intervention [@shamoa2023] similar enough to a diversity training [@chang2019] that you can pool the effects together into something that coherently reflects the effects of a class of intervention? In other words, can these designs and outcomes be pooled in a sensible way, or should separate strands of the research be evaluated separately? These questions come down to beliefs, and, as @slough2023 argue, cannot be resolved with statistics. A comprehensive and well-organized review is an indispensable tool for clarifying which questions to ask in the first place.

We also encourage authors not to be discouraged from writing meta-analyses of subjects that have been previously reviewed and analyzed, even many times. First, in our experience, simply reproducing the work of previous meta-analyses verbatim might generate surprises. For example, Pettigrew & Troop's landmark meta-analysis [-@pettigrew2006] identified 515 studies and 36 "true experiments" (p. 759) on intergroup contact; however, when we took a look at these papers for ourselves when writing @paluck2019, we found that many "were mislabeled as randomly assigned, did not feature 'actual face-to-face interaction' or did not have a non-contact control group;" between these issues and papers that lacked long-term outcome measurement, we ended up with nine experiments that met our inclusion criteria. 

Second, we share Munger's [-@munger2023] concern for "temporal validity:" because the conditions under which findings hold are likely to change over time, "no research design, no empirical knowledge, is perfectible" (p. 1). For instance, the implicit bias [@gawronski2019] and symbolic racism [@mcconahay1976; @sears2003] research agendas emerged because researchers observed a dramatic drop in how readily white Americans would express overtly racist ideas in the 1970s and 80s, which called for a paradigm shift in measurement. Meta-analyses are essential for assessing which classes of interventions still 'work' in light of such paradigm shifts. 

Third, as the credibility revolution spreads across the social sciences [@angrist2010; @samii2016; @vazire2018], we can generally expect recent research to meet comparatively higher standards of rigor and transparency, and therefore have a disproportionate impact on our understanding of the world. 

Fourth, even in fields with many systematic reviews, there's still often an open lane for a paper that's laser-focused on the findings of the best, most policy-relevant research [@paluck2019] or that's both comprehensive and quantitative. For instance, while reviewing prior papers on sexual violence for @porat2024, we found no theoretically comprehensive reviews that also had meta-analyses: all quantitative reviews were focused on smaller subsets of the literature. 

## Meta-scientific quantities illuminiated by meta-analysis

While the aims we articulated above could generally be met by a non-quantitative systematic review, meta-analysis is essential for assessing several meta-scientific outcomes.

### Publication bias
The first is publication bias. Classical approaches to assessing publication bias in meta-analysis are "based on the fact that precision in estimating the underlying treatment effect will increase as the sample size of component studies increases" [@egger1997]. The funnel plot detects publication bias under the assumption that smaller, more imprecisely estimated studies that produce null or backlash results are more likely to be shelved than large, precisely estimated studies that produce the same.^[The underlying theory of researcher behavior seems to be a kind of widespread acceptance of the sunk cost fallacy: once you've invested the kind of time and energy that a large, rigorous study requires, you'll push through to publication even if you'd put the results back in the 'file drawer' [@rosenthal1979] if you'd put less work in.] Alternatively, one can simply plot the relationship between effect size and standard error, as we did in @paluck2019, where the strong positive relationship between the two suggested that "a very large study would be expected to produce a minuscule *increase* in prejudice." These tests require estimates of effect size and variance for each study. 

Estimates of publication bias can also be interesting between meta-analyses. For instance, we found strong evidence of publication bias in @paluck2019 and @paluck2021 but not in @porat2024, which drew more from public health perspectives and departments than did the previous two papers. This kind of finding sheds light on whether, and along which dimensions, the credibility revolution is taking hold across disciplines.

### Comparisons across intervention strategies
Quantitative estimates allow for head-to-head tests of efficacy across different classes of interventions. For example, @paluck2021 estimated that the "20 experiments testing antibias, multicultural, and moral education programs" have an average effect size of *d* = 0.30, compared to *d* = 0.43 for 12 entertainment interventions. This does not necessarily mean that entertainment interventions reduce prejudice more effectively than antibias trainings do \textemdash there are many confounding differences between these two categories of study \textemdash but the differences do tell the reader something about how effectively people in different disciplines are manipulating the key quantity of interest by their own lights.

### Robustness to differences in study design
Third, relationships between effect and study design, measured in a variety of ways, are often illuminating. The most basic of these is whether studies were randomized or not. @porat2024, for example, finds a pooled effect size of 0.503 within observational designs, 0.287 for quasi-experiments, and 0.307 for randomized controlled trials. Another candidate is statistical power: @paluck2021 found a highly significant relationship between sample size and effect size, with the smallest quintile of studies producing an average effect of *d* = 0.61 vs *d* = 0.19 for the largest quintile. Last, researchers can check for robustness to adherence to open science practices; @paluck2019, for instance, found that studies with pre-analysis plans had an average effect size of 0.016, vs. 0.451 for everything else. 

We wish to emphasize that these are _not_ well-identified estimates of the 'effect' of study designs, sample sizes, or pre-analysis plans \textemdash none of these things were randomly assigned, and many other things varied between these studies \textemdash but it is at least a 'hoop test' [@collier2011] that something is amiss, e.g, that p-hacking is a problem in the contact hypothesis literature.

### Robustness to differences in measurement strategy

Fourth, quantitative estimates allow for assessing differences in effect size between outcomes and how they're measured. This can be interesting both within literatures and across them. The three meta-analyses discussed in this paper mostly measure attitudes, and their overall effect sizes all fall between 0.28 and 0.357: a relatively small range. However, for @porat2024, the key quantity of interest \textemdash sexual violence \textemdash is fundamentally a behavioral problem. There, our results are discouraging: pooled effect sizes of just 0.033 for perpetration outcomes and 0.046 for victimization, neither of which is statistically significant.^[Likewise, @green2024 look at interventions intended to reduce consumption of meat and animal products and only meta-analyze direct measures of what people eat \textemdash rather than what they think, feel or intend to do about what they eat \textemdash and find an average effect size of 0.131.] [SENTENCE ON DELAY IN OUTCOMES FOR PALUCK 2021]

## The trade-off between comprehensiveness and narrow, focused reviews

### Addressing contemporary criticisms by relaxing the causality assumption
@slough2023 and @simonsohn2022 have raised trenchant critiques about whether the typical meta-analytic estimate is meaningful. Both papers argue that meta-analyses should be more selective in what papers they include \textemdash @slough2023 to assure harmonization of the independent and dependent variables, and @simonsohn2022 to prevent mixing "studies of the highest quality" with "studies that lack internal validity" (p. XXX). 

Of our three meta-analyses, @paluck2019 most closely hews to this model of inquiry. That paper looked solely at randomized controlled trials where intergroup contact was the treatment variable and where there was at least a day of delay between the commencement of treatment and outcome measurement. (Admittedly we could have tightened our study even further by looking for harmonized dependent variables, but given the diversity of outcomes we found, that would have effectively precluded meta-analysis.) Our subsequent two meta-analyses [@paluck2021; @porat2024], are much more clearly at risk of the kinds of incoherence that recent critics identify. Both studies include a mixture of experiments, quasi-experiments, and observational designs (so long as there was a control group with pre- and post-treatment outcomes); combine papers that are drawing from vastly different theoretical traditions; and mix divergent dependent variables.

Each of these is a bias-variance trade-off. Conventional meta-analyses consistently resolve this trade-off in favor of reduced variance with only minimal attention to concordant bias. When this challenge *is* discussed, it's typically framed in terms of a desirable trade between internal and external validity: what's lost in terms of unbiased causal inference is appropriately compensated for by gains in knowledge about the diversity of settings in which a treatment works. (See @mathur2022 for discussion.)

We do not find this argument persuasive. As @thye2000 puts it, "if there are doubts or questions about whether a relationship is real or spurious, then whether or not the finding applies to other settings is irrelevant" (p. 1303). Moreover, this does not address potential bias introduced by non-harmonized treatments and outcomes. The threat there is not from confounders, but the much more conceptual problem that it simply doesn't make sense to pool what's being pooled. Consider the sexual violence literature, which includes, for instance, a building-based intervention comprising "higher levels of faculty/security presence in safe/unsafe 'hot spots' mapped by students" [@taylor2013], and a module of peer-based consent training on a college campus [@crane2017]. When you average these two things, what does the resulting quantity signify? Ascribing a causal meaning to that average \textemdash saying that both interventions are tests of the same core ideas, just in different settings \textemdash requires some strong additional assumptions. Likewise with dependent variables; in that paper, we coded the Sexual Experiences Survey [@koss1982, @koss1985] for behavioral outcomes and the Illinois Rape Myth Acceptance Scale [@thelan2022] for ideas-based outcomes when they were available, but the nearest substitutes for each, in our assessment, when they weren't. What additional assumptions do we need to argue that these multitudinous outcomes are coherently integrable?

We take a different tack: we drop the assumption that a pooled meta-analytic effect should be considered causal. Instead, when we combine studies from heterogeneous designs, treatments, and outcomes, the pooled estimate is a *descriptive statistic* representing the average size of changes measured by a group of researchers, according to them, with outcomes they chose. For @paluck2021, this number represented the average effects found by prejudice researchers between 2007 and 2019; for @porat2024, the average effects found by sexual violence researchers between 1986 and 2018.

We were not as clear about the distinction between descriptive and causal analyses as we should have been in our three previous meta-analyses. Our thinking on this matter has evolved over time and we aim to be clearer in future papers.

### The case for inclusive and comprehensive meta-analyses
We think there is value in inclusive searches and analyses, even if the resulting pooled estimate is not causal. First, coding all available studies allows for the most comprehensive possible assessments of publication bias, an essential meta-scientific quantity. 

Second, any difference in effect sizes between randomized and non-randomized interventions allows researchers to put a parameter value on the potential scope of confounding bias in the non-randomized literature. If the effect sizes are basically the same, that suggests that confounding is not a significant issue. On the other hand, if randomized interventions produce effect sizes that are on average *d* = 0.2 smaller, this suggests that future observational work can be 'discounted' by approximately that amount. This is obviously not a foolproof estimation strategy, but we think it's good start for for establishing a quantitative prior. 

Third, we think that the the initial pooled estimate provides a benchmark for all subsequent analyses, including those with sufficient internal validity and harmonization of treatments and outcomes to be plausibly causal. For example, the pooled effect observed in @porat2024 is 0.28, but just 0.086 for perpetration outcomes with randomized designs; of the 28 studies meeting these stricter inclusion criteria, 16 self-reported null results. This gap between, on the one hand, the superficially encouraging results of the literature as a whole and, on the other, the bleaker results from the best studies looking at the most crucial outcome, is a call to action to researchers. The contrast helps build the intuition that the literature's theoretical approaches are in need of a change of direction.

Fourth, how well different outcomes are harmonized or not is, in some cases, testable. In @porat2024, slightly fewer than half of studies measured acceptance of rape myths studies; fewer than that measured sexually violent behavior, and a comparatively small subset measured both. We found an overall random effects estimate of 0.071 for behavioral outcomes and 0.366 for ideas-based results. This divergence, we think, is _prima facie_ evidence that these outcomes represent different theoretical quantities and cannot be combined into a causal analysis. Researchers can help readers come to their own conclusions by separating data by dependent variable and presenting meta-analytic results side by side. 

Fifth, coding a wide variety of interventions allows for subsequent analyses to focus on the effects of particular interventions, or classes of intervention, and comparing them. Again, the overall meta-analytic estimate provides a backdrop to these more focused analyses.

Sixth, starting from a precise estimate, gleaned from hundreds of studies, and then moving to a much higher quality but sparser dataset of the very best studies, is an effective narrative device. This can also work between papers. Consider the contrast provided by @pettigrew2006 and @paluck2019. The former paper observes that across hundreds of studies comprising hundreds of thousands of people, contact typically reduces prejudice. The latter paper, however, notes that as of 2018, there had been zero evaluations of interracial contact in adults that had both random assignment and a delay of at least a single day between the beginning of treatment and outcome measurement. In other words, some essential basic research was missing. The apparent solidity of the first claim makes this absence all the more startling.

In sum, we see value in identifying, coding, and meta-analyzing heterogeneous estimates from study designs, interventions, and outcomes. However, a focused meta-analysis with strict inclusion criteria can also have appreciable impact on the field. So when is one strategy or the other appropriate?

We favor comprehensive meta-analyses if resources allow. On the one hand, these projects are much larger undertakings: @porat2024 took six years, five authors, and a team of RAs, whereas @paluck2019 was basically written in a summer by three people (although identifying the universe of relevant studies was partly accomplished during other projects). On the other hand, comprehensive meta-analyses help authors develop, and then impart to readers, a truly thorough understanding of the literature. For "The Leading Approach to Reducing Sexual Violence" in @porat2024, there was simply no substitute for reading hundreds of studies. (We'd also add that quantitative coding studies is a kind of enforcement mechanism for reading a paper closely.) Further, a more focused analysis of the very best studies can be encompassed within a comprehensive meta-analysis: the dataset assembled in @paluck2021 could (hypothetically) be filtered to reproduce the dataset of @paluck2019 precisely, but the reverse is not true.

However, a more focused meta-analysis can still be a very useful contribution, especially as a rejoinder to prior credulous reviews. We recommend that such papers choose inclusion criteria that select for validity on three fronts: design, contrast, and measurement. For example, @green2024 loos solely at estimates from randomized controlled trials that 1) measure MAP directly 2) at least a single day after treatment was administered with 3) at least 25 subjects in treatment and control (or 10 clusters for cluster-randomized trials). This has the pragmatic benefit of winnowing a literature with literally thousands of studies down to a few dozen, which makes for a much more tractable analysis and paper-writing process. 

Alternatively, researchers might split the difference between these approaches by conducting a theoretically comprehensive literature review, coding data from every study, but only meta-analyzing research that meets the paper's inclusion criteria.

We now turn to the pragmatic section of our paper, where we detail the typical structure of our meta-analytic papers, our analytic defaults, and an R package that implements those defaults. 

# Default structure and analytic choices for Paluck lab meta-analytic papers

We do not expect anything in this section to be groundbreaking or novel. However, we think there is pedagogical value in explicitly sharing a lab's approach to a class of paper. (Caveat that each paper was tailored to its venue and there is some variation between papers about where each of the following sections occurs.)

## How our meta-analyses typically unfold

Our meta-analyses' introductions describe the context and stakes of the paper. @paluck2019 and @porat2024 cover the major theoretical developments in their respective literatures, whereas @paluck2021 describes the need for an update on the major developments since a previous review [@paluck2009]. @porat2024 focuses particularly on 'zeitgeist' studies and ideas, which we think works nicely as a framing device for subsequent quantitative analyses, especially if some of those zeitgeist notions are revealed to have a surprising lack of evidence for their efficacy.

We then typically provide details about our database of studies and how we assembled it. These sections are pretty standard for meta-analyses, e.g. including our PRISMA diagrams [@moher2009], search terms, where and when our studies took place, and criteria for study collection.

Next, we detail our meta-analytic methods. These sections are not intended as exhaustive treatments of meta-analysis, but rather to detail a few important choices, e.g. how we selected dependent variables [@paluck2019], our contrasts between overall results and those from "studies with reasonably good statistical precision" [@paluck2021, p. 14.7], and how readers can access our original datasets and reproduce our analyses (all three papers). 

Next, we come to the main course: our meta-analyses. These sections are tailored to their literatures, and so follow distinct paths. However, we can describe a few general guiding principles.

First, we typically start big and then go small, meaning we start by meta-analyzing everything and then zoom in on different subsets of the literature. As we argued above, we think that starting big is an effective framing device for our more focused analyses. We typically follow this with various tests for publication bias, e.g. a plot of effect sizes by standard errors, a statistical summary of the relationship between the two, and tests for systematic differences in effect sizes found in published or unpublished studies.

Our more focused analyses typically apply the "split-apply-combine" framework for data analysis [@wickham2011]. For instance, in a literature with randomized controlled trials, quasi-experiments, and observational designs, as well as a mix of attitudinal and behavioral outcomes, we would present a 3 by 2 table where each subset of study design + outcome strategy gets its own meta-analytic estimate [table 2 in @porat2024]. Alternatively, in a literature with many similar but distinct quantities of interest, e.g. racial/ethnic prejudice vs. prejudice against LGBTQ+ people vs. prejudice against people with physical and mental disabilities, we would present the meta-analytic effects within each subset of data. These sub-analyses aim to identify two meta-scientific desiderata. The first is places where basic research has not yet been done, e.g. the finding in @paluck2019 of zero evaluations of interracial contact in adults with both random assignment and delayed measurement. The second is the subsets of data that have sufficient contrast and measurement harmonization to have plausible target equivalence. For instance, @porat2024 assessed the effects of interventions with a bystander component [@banyard2004; @banyard2007] on their own, and found null results on perpetration (0.019) and victimization (-0.009) outcomes. We conclude, unfortunately, "that nearly 1 in 3 studies in our database is pursuing a theory of behavior change that is not grounded in reality" (p. XXX). 

Finally, we aim to include tests of the relationship between study quality and effect size.

In a related vein, @porat2024 tested whether changes in ideas predicted changes in behaviors in studies that measured both, and found a disappointing lack of correlation between the two. This suggests that these classes of outcomes are not fundamentally assessing the same theoretical quantity, and that the paradigm on which this literature is based \textemdash myths about sexual violence cause sexual violence, so changing the myths should reduce the violence \textemdash does not seem to hold.

This typically concludes our meta-analytic sections, at which point we move to a discussion of open questions and next steps. Here we write specifically for researchers. In @porat2024, we highlight positive developments in measurement strategies as well as some viable theories of behavioral change that have yet to be tested. In @paluck2019, we encourage researchers to test which of the moderating conditions proposed in @allport1954 are most essential for anti-prejudicial effects, and call on researchers to fill in important gaps in basic research gaps. In @paluck2021, we discuss some concerning trends in measurement and design, and then celebrate seven 'landmark' studies. These papers "are exceptionally well-designed and executed" and "provide a glimpse of what a meta-analysis would reveal if we could weight studies by quality as well as quantity" (p. 14.19).

Further, because our meta-analyses tend to produce comparatively equivocal evidence for the efficacy of research programs, they provide an intellectual backdrop to researchers who find inconclusive or null results. For example, @scacco2018 and @mousa2020 ran landmark contact hypothesis papers that found much less salubrious effects than the literature's boosters might have expected; we hope that the analyses in @paluck2019 helped make these results seem more legible, and less like statistical anomalies, to readers.

## Default meta-analytic procedures in Paluck lab

Our meta-analytic procedures vary somewhat between papers. However, a few guiding principles have held constant, and we've also developed some techniques that we think are helpful for solving methodological issues.

First, at the level of condensing studies to estimates of effect size and variance, we use equations found in @cooper2019 to calculate standardized mean differences (SMD) \textemdash an average treatment effect divided by some measure of standard deviation of the dependent variable. While some literatures might all look at the same dependent variable, or all present the same statistical outcome (e.g. an odds ratio), we've never meta-analyzed a literature that does so.

When possible, we prefer Glass's $\Delta$ to Cohen's _d_. The difference is that $\Delta$ standardizes by the standard deviation of the dependent variable for the control group rather than the entire population. We prefer $\Delta$ because the experimental treatment might change some aspect of the distribution of outcomes for the treated subjects, and what we seek to know is the effect of treatment in terms of the underlying distribution of the untreated population. When the standard deviation of the control group's outcomes is not presented, we will standardize by whatever is available. (In practice, standard deviations between treatment and control groups tend to be very similar in papers we've analyzed).

When converting event outcomes, e.g. how often a sample of people reports perpetrating some behavior, to Glass's $\Delta$, we treat each event as draws from a Bernoulli distribution whose variance is $p (1-p)$ and whose standard deviation is $\sqrt{p(1-p)}$. If some event occurred in 15 out of 100 people in the control group and 10 out of 100 people in the treatment group, our estimate of Glass's $\Delta$ = $\frac{.1 - .15}{\sqrt{.15 * .85}} = -0.14$. We think this estimator has some desirable theoretical properties relative to conventional methods of converting odds ratios or log odds ratios to SMDs [@gomila2021]; we elaborate more on this in an appendix to @porat2024. 

In terms of aggregating studies for meta-analysis, we default to random effects estimates rather than fixed effects; in the heterogeneous literatures we analyze, there is likely no singular "true" effect size for which we are searching, but rather a variety of true effect sizes moderated by populations, conditions, and intervention strategies. We cluster standard errors at the level of study, rather than paper or team of authors or lab group, because we assume that the bulk of correlation between outcomes takes place within studies. 

### Implementation with an R package
We have written a collection of functions to help implement these defaults, and write papers that use them, called `PaluckMetaSOP.` It is available at <http://www.github.com/setgree/PaluckMetaSOP>. Its functions fall into three categories.

First, we wrote functions to convert unstandardized effect sizes into standardized mean differences. `d_calc.R` takes a statistical result, sample sizes for treatment and control, a measure of standard deviation, and a class of statistical test and returns an SMD. `var_d_calc.R` does the same thing for estimates of variance and standard error. `dip_calc` is a helper function that does so for difference in proportions estimates.

Next we have functions that help us report meta-analytic results. `map_robust.R` is a wrapper around the core meta-analytic functions in the `metafor` package [@viechtbauer2010] that integrates well into the `purrr` package from `tidyverse` [@wickham2019], and therefore helps us implement the split-apply-combine framework [@wickham2011]. `study_count.R`, `sum_lm.R` and `sum_tab.R` do the same for existing functions that count the studies in subsets, compute and report linear regression results, and report frequency tables. 

Finally, we have functions that make writing meta-analysis papers easier. This paper was drafted as an Rmarkdown file using the `papaja` package [@R-papaja], and we've written some additional functions that, for instance, combine Rmarkdown rendering, `git add` and `git push` into a single command; convert DOIs to a bibliography; and record a computational environment as a Dockerfile [@moreau2023].

Please see the package's vignette on <http://www.github.com/setgree/PaluckMetaSOP> for detailed usage instructions with reference to a demonstrative subset of the data from @paluck2021. 

# Conclusions: hard cases

A classic paper on meta-analysis defines the procedure as "a statistical analysis which combines or integrates the results of several independent clinical trials considered by the analyst to be ‘combinable'" (p. XXX). Our (non-systematic) review of prior meta-analyses reveals a surprising dearth of attention to how much theoretical work is being done by the phrase "considered by the analyst to be 'combinable.'" @simonsohn2022 argue that researchers who "uncritically" aggregate results from all available studies, as part of an "active effort to eliminate publication bias...might instead amplify the bias from poor research design and execution" (p. XXX). We agree with this assessment, but would instead frame it as one of three crucial bias-variance trade-offs facing meta-analysts. By combining studies with non-comparable designs, interventions, and outcomes, researchers give readers the impression of remarkable precision (re: reduced variance) but at the expense of introducing non-statistical sources of uncertainty (re: bias) on all three fronts. Only by acknowledging these trade-offs head-on, and devising techniques for dealing with them, can we write meta-analyses that are fundamentally incredulous, evaluative, and careful about causal inference: in a word, meta-scientific. 

More broadly, this paper seeks to answer two questions: what are we aiming to do when we meta-analyze, and how do we do it? We hope that we've answered these questions to some extent, but many open questions remain. To us, the most pressing issues arise from a lack of clarity about whether meta-analyses are, or should be, hypothesis-driven. Typical checks on researcher degrees of freedom [@gelman2013; @simonsohn2014] assume a hypothesis-driven framework, and indeed, meta-analyses in the social sciences are usually aimed at validating pre-existing hypotheses. Ours, however, are more exploratory: we aim for evaluation rather than validation. While we might start with some general hypotheses, these might be about a discipline rather than a literature. For example, our prior is that a social psychology literature from the 2000s is likely to show evidence of selection pressures for statistical significance. However, we also develop many of our most important questions after reading papers, which, in the context of writing a meta-analysis, means after data collection has begun. In other words, our meta-analyses are both inductive and deductive inquiries. We are left with a conundrum: we wish to "tie our hands to the mast" [@elster1977], e.g. by writing detailed pre-analysis plans and sticking to them, while also acknowledging that the most incisive questions often emerge after reading and coding studies, i.e. after data collection has begun. 

Further, meta-analyses that are written before data collection are at risk of going off track by proceeding from false premises. Consider a mistake we made while composing the pre-analysis plan for @porat2024. Because we are accustomed to social psychology literatures, we registered the analysis that we would evaluate "the overall effect size of behavioral outcomes for all of the studies in the dataset, both in the short- and in the long-term." The idea was to measure if effects of interventions attenuate over time, which is a serious concern in psychology. However, while some behavioral outcomes in the sexual violence literature are measured immediately (e.g. whether someone volunteers for a campus rape education organization [@gillies1997]), most behavioral outcomes need time to accumulate. The Sexual Experiences Survey (SES) measures incidents of sexual violence in a given time period, and an SES administered at the end of a semester is essentially guaranteed to have more incidents than one given immediately after an intervention concludes. This only became clear to us after we began reading papers (though someone with better foresight could have anticipated the issue).

The way we resolved this was to make sure that we included, either in the paper or in an appendix, every single pre-registered analysis, even when they were not especially informative, and to explain the above issue in our appendix. Moving forward, we aim to have pre-specified analysis code run on simulated data [@broockman2016; @blair2019] and to devote more time to anticipating such issues. However, this is still a work in progress at our lab.

Second, we sometimes encounter indirect signals of study quality in the literature that are difficult to integrate into formal inclusion and exclusion criteria. Should we exclude a study because it has an implausibly *large* effect size, e.g. a t-test value of 36? (One study in the prejudice reduction literature did.) What about errors in the text, or obvious discrepancies between results reported in the text and those in a table? What about a lack of transparent reporting that leads to our spending substantial time guessing a study's true effects? Each of these is information about a study's true quality; as @simonsohn2022 argue, excluding these studies would be the same "kind of meritocratic screening of research" that we "engage in when performing virtually every other task in [our] professional research lives." Conversely, we might notice that a paper pays special attention to computational reproducibility, or was published in a journal where reproducibility checks are part of the publication process [@lowe2021]; this is also a signal of study quality in the opposite direction. Some of these data points are easy to code, e.g. data availability, and can be included in our meta-analyses; but some are not, e.g. a the sensibility of a paper's statistical approaches.

There are clearly no easy answers to this problem, but we've developed general guidelines as we've progressed. One is that cluster RCTs with fewer than 10 clusters in total are so underpowered that they are effectively quasi-experiments, and we coded them as such in @porat2024. Another is that we do not code studies where we need to eyeball a figure to assess effect sizes: researchers should not make us guess. Likewise, we do not convert "the results were significant" or simply "p \< .05" into quantitative estimates. However, if authors tell us that a result was "null" or "not significant" but say anything more, we set the result to be 0.01. These rules are not perfect, but ultimately, we need policies that balance type I errors (including a study we should exclude) and type II errors (excluding studies we should include). Like research itself, we suspect that this task is not perfectible.

Last, there is a great deal of subjectivity in figuring out what outcomes to code. For @porat2024, we found relative homogeneity of dependent variables, but not so for @paluck2019 or @paluck2021. In the end,this has always been a judgment call, but as we continue writing meta-analyses, we hope to develop principled, general guidelines for this kind of analytic choice.

These open questions notwithstanding, we think meta-analyses can be useful, informative, and a pleasure to write and read. We hope to see them become a standard part of the meta-scientist's toolkit, and likewise for all meta-analyses to become more meta-scientific.

# References
