---
title: "Hard cases: non-standard conversions of studies into SMDs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hard cases: non-standard conversions of studies into SMDs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The 'proper' way to convert statistical results into ∆ is a topic of debate among researchers. In practice, we find the differences between different estimation strategies to be not especially meaningful, and the equations we use in these functions have served us well through three papers. However, for each paper, there have been some hard cases that required some bespoke solutions. We discuss these more in a separate vignette.

In general, we make all available efforts to figure out a "good enough" estimate of ∆, but if we really can't figure something out, we'll omit it or just include the study as part of a vote counting procedure (a tally of statistically significant positive, statistically significant negative, and null results).


TODO: figure out a way to extract just the needed values (t-test for whatever), and run it 1000 times with different values of n, and see hwo close each is to the true D average. Maybe 1000 simulations per N value of 100, 1000, and 10000
and figure out what to do with RSE??
```{r simulation}

library(dplyr)
library(PaluckMetaSOP)
dat <- data.frame(unique_study_id = 1:10000,
                  treatment_status = rbinom(n = 10000, size = 1, prob = 0.5)) |> 
                    mutate(outcome = if_else(treatment_status == 1, rnorm(10000, 2, 1),
                                    rnorm(10000, 1.5, 1)),
                           cov_one = if_else(treatment_status == 1, 
                                             sample(2:5, replace = T, size = 10000),
                                             sample(1:4, replace = T, size = 10000)),
                           cov_two = if_else(treatment_status == 1,
                                             rnorm(10000, 5, 1),
                                             rnorm(10000, 4, 1)))

true_pop_sd <- sd(dat$outcome)
# Calculate mean outcome for the treatment group
true_mean_diff <- mean(dat$outcome[dat$treatment_status == 1]) - 
  mean(dat$outcome[dat$treatment_status == 0])

true_d <- true_mean_diff / true_pop_sd
n_c <- sum(dat$treatment_status == 0)
n_t <- sum(dat$treatment_status == 1)
simple_model <- summary(lm(formula = outcome ~ treatment_status, data = dat)); simple_model
cov_model <- summary(lm(formula = outcome ~ treatment_status + cov_one + cov_two, data = dat)); cov_model



# put in the numbers from simple_model and calculate distance from true d
d_calc(stat_type = "t_test", stat = 26.46, n_t = n_t, n_c = n_c) - true_d  # 0.01740734

# now the numbers from the model with covariates
d_calc(stat_type = "t_test", stat = 22.440, n_t = n_t, n_c = n_c) - true_d # 0.06259266
```

