---
title: "An overview of these vignettes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{An overview of these vignettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1 Meta-analysis is (more or less) a six step process.

1)  Identify a causal question where combining results from many papers will be informative.[^1]

2)  Decide which papers shed light on that question.[^2]

3)  Gather and read all such papers (re: conduct a systematic search).

4)  Condense each study's results to a single point estimate, or a cluster of point estimates, and associated variance(s).

5)  Aggregate those estimates into a pooled average effect and any relevant subgroup effects.

6)  Write up your results.

[^1]: For instance, you might want to assess scope condition under which an effect can be expected; identify cross-study moderators that predict population- or setting-level effects that can be expected to strengthen or weaken effects; or put multiple theoretical approaches head to head to see which one works best. The alternative to a meta-analysis for assessing the relationship between X and Y is to run an experiment. But a meta-analysis can be very helpful in figuring out what that experiment should look like by illuminating gaps in the literature.

[^2]: In practice this means operationalizing X and Y, which might not be straightforward: does imagined contact count as contact? What exactly is prejudice, and how do we measure it? It also means setting inclusion criteria related to, e.g., internal validity, measurement error, or population. For instance, your meta-analysis might be focused only on the results of [policy-relevant randomized controlled trials](https://www.cambridge.org/core/journals/behavioural-public-policy/article/contact-hypothesis-reevaluated/142C913E7FA9E121277B29E994124EC5), a [particular class of dependent variable](https://osf.io/a7g95/), or the effects of [sexual violence prevention programs on college campuses](https://www.jahonline.org/article/S1054-139X(23)00117-9/abstract).

## 2 These vignettes are aimed at steps 4-6.

The [first vignette](d-calc-vignette.html) is about **step 4**, effect sizes and variance. It covers "easy" cases where you can use `d_calc` and `var_d_calc` without too much extra work, then walks through a few edge cases we've encountered over time. Finally, it demonstrates how to incorporate these functions into your analysis scripts in a reproducible way.

The [second vignette](meta-analysis-vignette.html) is about **step 5**, how to actually do meta-analysis. It covers using `map_robust` to combine your point estimates and variances into pooled estimates for the population and any subgroups you want to analyze.

The [third vignette](writing-metas-vignette.html) is about **step 6**, and walks through the other functions we've written to help write a meta-analysis paper. Specifically, it covers `sum_lm`, `sum_tab`, and `study_count`, as well as a few smaller functions for turning a meta-analytic database into a bibliography and creating ggplot2-based visualizations.

## 3 Next up

[Converting a study's results into SMD, variance, and standard error](d-calc-vignette.html).
